version: "3"
services:
  backend-nodejs:
    build:
      context: ./backend-ts
      dockerfile: Dockerfile
    environment:
      - ENV_NAME=dev
      - PORT=3001
      - CACHE_HOST=redis-server
      - CACHE_PORT=6379
    ports:
      - 3001:3001
    expose:
      - 3001
  fronend-react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - ENV_NAME=dev
      - REACT_APP_API_HOST=http://localhost:3001
    expose:
      - 3000
    ports:
    - 3000:3000
    stdin_open: true
  redis-server:
    image: "redis:alpine"